#!/usr/bin/env ruby

CHECKERS = [
  'bundle exec rubocop',
  'srb typecheck',
  'bundle exec brakeman --exit-on-warn --no-summary',
  'bundle exec rails test'
].freeze

exit(1) if CHECKERS.any? { |script| !system(script) }